### ISSUE TITLE
load model more than 1000 epochs

### ISSUE THREAD

**Issue by masaikk** [GANtastic3/MaskCycleGAN-VC#1]
If I want to continue the train after it have train more than 1,000 epochs for example 1,200,  set the --continue_train and set --load_epoch as 1200 in train.py, it will have a error path. In model_saver.py line 76, it set the path to model to be loaded have only three digits.

**Comment by hikaruhotta** [comment]
Thank you @masaikk for pointing this out. The epoch is now represented as 5 digits.
