### ISSUE TITLE
Optimal duration of audio for source and target

### ISSUE THREAD

**Issue by faranaziz** [GANtastic3/MaskCycleGAN-VC#11]
Hello, 
What is the optimal duration?
Is there any advantage to using 4 hour for a target and 2 hours for a source?  or 4 hours for the source? I can definitely hear differences when the duration is longer, e.g 30 minutes vs 2 hours. 

Thanks

**Comment by hikaruhotta** [comment]
The more training data you can have for both the source and the target the better, but it may take longer to see good results.
