### ISSUE TITLE
How to use it with non-parallel data?

### ISSUE THREAD

**Issue by BenRafatian** [GANtastic3/MaskCycleGAN-VC#17]
I was wondering that if I could use 2 sets of non-parallel voice datasets, where each speaker utters completely different sentences, and there is no transcript of the data. 

also, does this program use end-end conversion, or does it train a speech-to-text model and then recreates the speech in the converted voice from the text?

**Comment by hikaruhotta** [comment]
MaskCycleGAN-VC is for non-parallel voice conversion so your dataset would work!

The model does end-to-end conversion meaning that it converts mel-spectrograms to mel-spectrograms

**Comment by BenRafatian** [comment]
Thank you @HikaruHotta for your help.
