### ISSUE TITLE
Controllable Generation

### ISSUE THREAD

**Issue by Pasinduekanayake** [GANtastic3/MaskCycleGAN-VC#20]
Hi, 

Thanks for the well-documented implementation and the outputs from the model are really good. I know the original paper was built for 1 to 1 conversion but I'm wondering if there's any possibility to control the output by manipulating the z vector input for the generator by using a pre-trained classifier. For example, if I train one source speaker to multiple target speakers(recordings of multiple speakers in one dataset acting as one target) and train a classifier to differentiate each speaker, will it be possible to control the output for the target we want. I'm just wondering whether the structure of this model will allow it? A reply would be highly appreciated since I'm trying to use this implementation for my undergraduate final year project in a couple of months. Thanks!

**Comment by hikaruhotta** [comment]
Hi @Pasinduekanayake, sorry for taking some time to get back to you. I'm happy to chat about this. Would you mind sending me a DM on linkedin?

**Comment by Pasinduekanayake** [comment]
> Hi @Pasinduekanayake, sorry for taking some time to get back to you. I'm happy to chat about this. Would you mind sending me a DM on linkedin?
