### ISSUE TITLE
Can't set it up on windows

### ISSUE THREAD

**Issue by BenRafatian** [GANtastic3/MaskCycleGAN-VC#4]
Tried to run the conda command but it seems to have a problem getting the packages. what should I do?

**Comment by terbed** [comment]
Yes, it is because the generated conda requirement is not cross-platform, I assume it was generated for Linux. You can set up a Linux subsystem in windows and or simply use Linux instead.

**Comment by BenRafatian** [comment]
> Yes, it is because the generated conda requirement is not cross-platform, I assume it was generated for Linux. You can set up a Linux subsystem in windows and or simply use Linux instead.

Thanks, mate.
