### ISSUE TITLE
hardware environment

### ISSUE THREAD

**Issue by MiracleYyds** [GANtastic3/MaskCycleGAN-VC#6]
Hi, I was very surprised to find this project.
Would you mind telling me what the configuration of your experimental hardware environment is? Such as how many RAM is needed for the graphics card.
And,  how long it will take after several hundred epochs training to get excellent results? 
Thank you.

**Comment by hikaruhotta** [comment]
A single GPU with 8GB of RAM should be sufficient to train the model with a batch size of 1.
It trained 3500 epochs (6 epochs per minute) in less than a day on a Quadro RTX 8000. However, the model often converges much earlier than this (1000 epochs) so I would not expect training to take longer than 2 days on most GPUs.

**Comment by mengxiangjiacherry** [comment]
Thank you very much. 
In addition, I also looked at CycleGan-VC2 to see if the model has no restrictions on languages, or only English.
I'm new to this and I apologize for bringing this up. I will be very lucky to have your guidance and help.

**Comment by mengxiangjiacherry** [comment]
> A single GPU with 8GB of RAM should be sufficient to train the model with a batch size of 1.
> It trained 3500 epochs (6 epochs per minute) in less than a day on a Quadro RTX 8000. However, the model often converges much earlier than this (1000 epochs) so I would not expect training to take longer than 2 days on most GPUs.

**Comment by MiracleYyds** [comment]
> A single GPU with 8GB of RAM should be sufficient to train the model with a batch size of 1.
> It trained 3500 epochs (6 epochs per minute) in less than a day on a Quadro RTX 8000. However, the model often converges much earlier than this (1000 epochs) so I would not expect training to take longer than 2 days on most GPUs.

Thank you very much.
In addition, I also looked at CycleGan-VC2 to see if the model has no restrictions on languages, or only English.
I'm new to this and I apologize for bringing this up. I will be very lucky to have your guidance and help.
